### ISSUE TITLE
Add modes cg-grayscale and cg-highcontrast

### ISSUE THREAD

**Issue by breznak** [maandree/cg-tools#1]
One of my monitors has a HW grayscale mode, I use it for eye-strain, it's even better than redshift. 
Another mode "high contrast" could focus on pleople with worse sight. It could start as black/white or gray-scale with focus on the 2 extremes; and develop further.

**Comment by maandree** [comment]
Unfortunately greyscale mode cannot be implemented here because it requires more than just gamma ramp manipulation, it is something you would have to implement in a compositor.

High contrast with colours can be implemented.

**Comment by maandree** [comment]
Sorry, I just woke up so I forgot that you could use 4×4 matrices in colour space manipulation so you don't need do implement greyscale mode in the compositor, but you cannot implement it in cg-tools either.

**Comment by maandree** [comment]
High-contrast mode will be release soon (it will be called cg-shallow), closing since almost done and greyscale is impossible.

**Comment by maandree** [comment]
Actually, what I will do is, I will see if I can extend an X compositor with the cooperative affine colour transformation, it will probably be slow as dogshit as I will probably not make it accelerated, at least at the beginning, but it will give us something to work with.
